language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - sh build/build_and_test_all.sh
#deploy:
  #  provider: surge
  #  skip_cleanup: true
  #  domain: <my_name_here>.surge.sh
  #  project: ./build/
on:
  branch: master
